typography_spectrum: 0.01604
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6039666628930718
  lightness: 0.20466652838513255
  saturation: 0.03274351358413696
  rhythmicContrast: 0.13423613877967
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: joineva
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Let's Change The World
purpose: []
